version: '3'

services:
  nginx:
    container_name: snginx
    image: nginx:alpine
    networks:
      - proxynet
    restart: always
    depends_on:
      - snode0
      - snode2
    ports:
      - "1317-1318:1317-1318"
      - "26657-26658:26657-26658"
      - "9090-9091:9090-9091"
    volumes:
      - ./testnet/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./testnet/nginx/certs:/etc/nginx/certs
  snode0:
    container_name: snode0
    image: "thesesamelab/sesamenet:latest"
    restart: always
    networks:
      - proxynet
    hostname: snode0
    expose:
      - 26656
      - 26657
      - 9090
      - 9091
      - 1317
      - 26658
      - 26660
    volumes:
      - ./testnet/node0:/root/.sesamenet
      - ./testnet/script:/app/script:ro
    command:
      - sesame
      - start
      - --p2p.persistent_peers
      - ${NODE1ID}@${NODE1IP}:26656,${NODE2ID}@${NODE2IP}:26656,${NODE3ID}@${NODE3IP}:26656,${NODE4ID}@${NODE4IP}:26656
      - --rpc.laddr
      - tcp://0.0.0.0:26657
      - --log_level
      - info
      - --trace
  snode1:
    container_name: snode1
    restart: always
    hostname: snode1
    networks:
      - proxynet
    image: "thesesamelab/sesamenet:latest"
    expose:
      - 26656
      - 26657
      - 9090
      - 9091
      - 1317
      - 26658
      - 26660
    volumes:
      - ./testnet/node1:/root/.sesamenet
    command:
      - sesame
      - start
      - --p2p.persistent_peers
      - ${NODE0ID}@${NODE0IP}:26656,${NODE2ID}@${NODE2IP}:26656,${NODE3ID}@${NODE3IP}:26656,${NODE4ID}@${NODE4IP}:26656
      - --rpc.laddr
      - tcp://0.0.0.0:26657
  snode2:
    container_name: snode2
    restart: always
    hostname: snode2
    networks:
      - proxynet
    image: "thesesamelab/sesamenet:latest"
    expose:
      - 26656
      - 26657
      - 9090
      - 9091
      - 1317
      - 26658
      - 26660
    volumes:
      - ./testnet/node2:/root/.sesamenet
    command:
      - sesame
      - start
      - --p2p.persistent_peers
      - ${NODE1ID}@${NODE1IP}:26656,${NODE0ID}@${NODE0IP}:26656,${NODE3ID}@${NODE3IP}:26656,${NODE4ID}@${NODE4IP}:26656
      - --rpc.laddr
      - tcp://0.0.0.0:26657
  snode3:
    container_name: snode3
    image: "thesesamelab/sesamenet:latest"
    restart: always
    hostname: snode3
    networks:
      - proxynet
    expose:
      - 26656
      - 26657
      - 9090
      - 9091
      - 1317
      - 26658
      - 26660
    volumes:
      - ./testnet/node3:/root/.sesamenet
    command:
      - sesame
      - start
      - --p2p.persistent_peers
      - ${NODE1ID}@${NODE1IP}:26656,${NODE2ID}@${NODE2IP}:26656,${NODE0ID}@${NODE0IP}:26656,${NODE4ID}@${NODE4IP}:26656
      - --rpc.laddr
      - tcp://0.0.0.0:26657
  snode4:
    container_name: snode4
    image: "thesesamelab/sesamenet:latest"
    restart: always
    hostname: snode4
    networks:
      - proxynet
    expose:
      - 26656
      - 26657
      - 9090
      - 9091
      - 1317
      - 26658
      - 26660
    volumes:
      - ./testnet/node4:/root/.sesamenet
    command:
      - sesame
      - start
      - --p2p.persistent_peers
      - ${NODE1ID}@${NODE1IP}:26656,${NODE2ID}@${NODE2IP}:26656,${NODE0ID}@${NODE0IP}:26656,${NODE3ID}@${NODE3IP}:26656
      - --rpc.laddr
      - tcp://0.0.0.0:26657
networks:
  proxynet:
    name: sesameNetwork